### ISSUE TITLE
make error: use of undeclared identifier 'iota' 

### ISSUE THREAD

**Issue by cn0xroot** [hahnpv/gr-gps#1]
hi,when i building gr-gps on mac :
```
➜  build git:(master) make
Scanning dependencies of target gnuradio-gps
[  4%] Building CXX object lib/CMakeFiles/gnuradio-gps.dir/acquisition_impl.cc.o
/Users/xxx/gr-gps/lib/acquisition_impl.cc:203:3: error: use of undeclared identifier 'iota'
  iota(carrier.begin(), carrier.end(), 1.);
  ^
1 error generated.
make[2]: *** [lib/CMakeFiles/gnuradio-gps.dir/acquisition_impl.cc.o] Error 1
make[1]: *** [lib/CMakeFiles/gnuradio-gps.dir/all] Error 2
make: *** [all] Error 2
```
how to fix it?

**Comment by hahnpv** [comment]
iota is part of std::numeric, the standard c++ libraries. You might try
adding an explicit

#include <numeric>

in acquisition_impl.cc

Please note this is NOT a complete GPS receiver. Right now the only fully
working block is acquisition. This is a project to help develop my GNU
Radio development skills and will likely never be a complete solution. I'd
suggest checking out gnss-sdr.org if you are looking for a code built on
GNU Radio, or SoftGNSS for an easy-to-read Matlab code (if you are looking
to learn) https://github.com/hahnpv/SoftGNSS

philip

**Comment by cn0xroot** [comment]
@hahnpv thanks for your help, i'll try again
