### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by jacquesbotha** [hahnpv/gr-gps#2]
Not sure how to contact you ...

Try this link: http://sbc.minipage.info

I need to re-write the g-code interpreter, but this version seems workable for now.

It will add software compensation to your g-code.  email me at <> if you find any bugs (there is bound to be some)

Jacques

**Comment by hahnpv** [comment]
Thanks Jacques. Will email you.

**Comment by jacquesbotha** [comment]
Sure thing.

I don’t mind sharing the code.

The main part is detecting the g2&g3 arcs and then splitting them at 0, 90,
180 & 270 (if needed), and then simply adding in backlash (and kept track
to add it to the next block until the machine reverses)

Would be better to write a python script, then you could add as a part of
your tool chain.

The code I wrote is in PHP, so hope you can extract bits from it.
